### PR TITLE
Tape inspired saturation

### PR DESCRIPTION
**Pull request by g-erson**
Howdy! I've been loving your script, but I really wished there was a more 'tape-like' saturation effect, so I've done my best to add one. Let me know what you think :) cheers

### CODE REVIEW

**Comment by justmat** [comment]
howdy! i love this idea! i'll load it up this afternoon and get back to you. very excited :)

**Comment by justmat** [comment]
spent some time playing with this last night and wowee, it sounds really good! i'll merge this now and make a lines post after i do some param menu cleanup and default value changes that i've been putting off :) thanks so much for the contribution!

**Comment by g-erson** [comment]
Thanks so much! I spent a while trying to 'tune' it to sound good in different contexts, and not presenting too many params. My name on lines is 'ganders' :) cheers!

**Comment by justmat** [comment]
I was just about to ask your lines handle!

**Pull request merged**
