### PR TITLE
hnds.lua - fix sine phase jump

### PR DESCRIPTION
**Pull request by crimclark**
- make square derived from sine
- fix initial waveform
- add depth param

### CODE REVIEW

**Comment by justmat** [comment]
thanks for taking the initiative with this! very appreciated :) 

thinking about it, i wonder if the addition of a depth param eliminates the need for min/max lfo params? 

i'll be able to test and pull this evening.

**Comment by crimclark** [comment]
Yeah, I was thinking the same thing about min/max lfo params. You should be able to achieve the same behavior with depth and offset. Of course removing those would also require updating otis.lua

Also, instead of doing things like this in otis.lua: 

`params:set(lfo_targets[target], lfo.scale(lfo[i].slope, -1.0, 1.0, params:get(i .. "lfo_min") + offset, params:get(i .. "lfo_max") + offset) * 0.01)
`

Could also maybe move the "+ offset" code to hnds (like where I multiply the depth), so otis.lua (or any other script using hnds) doesn't have to worry about that calculation.

**Comment by justmat** [comment]
These are great suggestions!

**Comment by crimclark** [comment]
Added another commit to remove min/max and move offset to hnds

**Comment by justmat** [comment]
I apologize for slacking on this! I forgot about a social engagement this evening, and haven't had a chance to dive in yet. I have an open schedule tomorrow, and will attend to things then. Very excited about shoring up hnds!

**Comment by crimclark** [comment]
no worries, and no rush! hope you like the changes and I didn't break anything haha :) would love to see hnds developed further and get used in more norns scripts

**Comment by justmat** [comment]
Just checked this out, and offset + depth seems to work as expected. I am going to play around with it today, and likely merge tonight. Thanks again! I like this much more than the min/max way I was doing it before.

**Pull request merged**
